// =============================================================================
// ft-lint — the fractalthemer contract linter.
//
// Ported from the affedo lint lineage (cui-lint) and inverted for the system
// boundary: affedo lints components GENERATED by the system against the token
// contract; this lints code that CONSUMES the system against the registry.
//
// Two modes:
//
//   self   (no arguments, inside this repo)
//     - registry freshness: rebuild must be a no-op ("already fresh")
//     - every src/**/*.svelte: no scoped <style>, no style= attribute
//     - every class used in templates exists in registry.json
//
//   consumer  (`fractalthemer lint <dir>` in a project that depends on this)
//     - same Svelte rules across the project
//     - token purity on its stylesheets: no raw hex, >2px budget, every
//       var() resolves to a registry token or a locally-defined property
//     - unknown-class check where the allowlist is:
//         CANONICAL registry layers ∪ classes declared in _08_own.sass
//       The target's compiled registry is NOT the allowlist — it absorbs
//       every local skin, which would legitimize component-declared classes.
//       A class found in a project-specific registry layer (component skins,
//       docs surfaces) is its own violation: ft/declaration-outside-own.
//     - a class declared in _08_own.sass that collides with a registry class
//       is an explicit conflict — layer 08 extends the system, never shadows it
//
// Exit code 1 on any error; --json for CI/agent consumption.
// =============================================================================

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadRegistry } from './lib/registry.mjs';
import { lintSvelteFile } from './lib/svelte-linter.mjs';
import { TokenLinter } from './lib/token-linter.mjs';
import { lintUninterpolatedFunctions, lintHardcodedRadius } from './lib/sass-linter.mjs';
import { findClosestMatches } from './lib/fuzzy.mjs';
import { reportDiagnostics } from './lib/agent-reporter.mjs';
import { runEject } from './eject.mjs';
import { runModeInstall } from './install-mode.mjs';
import { runBrowser } from './browser.mjs';

const PKG_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REGISTRY = path.join(PKG_ROOT, 'src', 'lib', 'data', 'registry.json');

function usage() {
	console.log(`Usage:
  fractalthemer lint              # self mode: lint this repository
  fractalthemer lint <dir>        # consumer mode: lint a project directory
  fractalthemer eject [dir]       # copy the styles into your project as yours
  fractalthemer mode [dir]        # install the mode-toggle feature as source
  fractalthemer browser [dir]     # open the class registry as a searchable page
Options:
  --own <file>    extension stylesheet (default <dir>/_08_own.sass)
  --registry <f>  registry.json override (consumer mode)
  --force         eject: overwrite files that already exist
  --json          machine-readable diagnostics
  --help`);
}

// --- file walking -----------------------------------------------------------

const SVELTE = /\.svelte$/;
const STYLESHEET = /\.(sass|scss|css)$/;

function walk(dir, filter, out = [], base = dir) {
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		if (entry.name === 'node_modules' || entry.name === '.svelte-kit' || entry.name === 'dist' || entry.name.startsWith('.')) continue;
		const full = path.join(base, entry.name);
		if (entry.isDirectory()) walk(full, filter, out, full);
		else if (filter(entry.name)) out.push(full);
	}
	return out;
}

const rel = (root, file) => path.relative(root, file);

// --- class allowlist ---------------------------------------------------------

/** Class selectors declared in an extension stylesheet (top of selector only). */
function harvestOwnClasses(content) {
	const names = new Set();
	for (const m of content.matchAll(/(?:^|[\s,{}])(\.)([a-zA-Z][a-zA-Z0-9_-]*)/g)) {
		names.add(m[2]);
	}
	return names;
}

// --- self mode ---------------------------------------------------------------

async function lintSelf() {
	const diagnostics = [];

	// 1. Registry freshness — the rebuild must say "already fresh". A diff
	// means the committed registry does not match the layer sources.
	let fresh = false;
	try {
		const stdout = execFileSync('node', [path.join(PKG_ROOT, 'scripts', 'build-registry.mjs')], {
			cwd: PKG_ROOT,
			encoding: 'utf8'
		});
		fresh = stdout.includes('already fresh, nothing written');
	} catch {
		fresh = false;
	}
	if (!fresh) {
		diagnostics.push({
			rule: 'ft/registry-stale',
			severity: 'error',
			file: rel(PKG_ROOT, REGISTRY),
			found: 'registry.json out of date',
			rationale: 'The committed registry no longer matches what the layer partials emit — every class check below would run against a lie.',
			suggestion: 'Run "pnpm registry", review the diff, and commit it.'
		});
	}

	const { classes } = loadRegistry(REGISTRY);

	// 2. Svelte contract + class membership.
	for (const file of walk(path.join(PKG_ROOT, 'src'), (name) => SVELTE.test(name))) {
		const source = fs.readFileSync(file, 'utf8');
		const relPath = rel(PKG_ROOT, file);
		const { diagnostics: svelteDiags, classes: used } = lintSvelteFile(relPath, source);
		diagnostics.push(...svelteDiags);

		for (const name of used) {
			if (classes.has(name)) continue;
			const closest = findClosestMatches(name, classes, 3, 4);
			const suggestion =
				closest.length > 0
					? `Did you mean '${closest[0]}'?\n  - other candidates: ${closest.join(', ')}`
					: `Class ".${name}" is not in the registry. Extend the system layer that owns the concern, or use an existing class.`;
			diagnostics.push({
				rule: 'ft/unknown-class',
				severity: 'error',
				file: relPath,
				found: `.${name}`,
				rationale: 'The registry is the complete inventory of the system. A class outside it is unaccounted-for styling.',
				suggestion
			});
		}
	}

	// 3. Sass layers: the literal-parse rule guards the system's own layer
	// partials — the bug class it flags actually shipped inside 09_modifiers
	// once (a raw list.nth() landing in the compiled CSS verbatim).
	for (const file of walk(path.join(PKG_ROOT, 'src'), (name) => STYLESHEET.test(name))) {
		diagnostics.push(...lintUninterpolatedFunctions(rel(PKG_ROOT, file), fs.readFileSync(file, 'utf8')));
	}

	return diagnostics;
}

// --- consumer mode -----------------------------------------------------------

function lintConsumer(targetDir, options) {
	const { ownPath, registryPath } = options;
	const diagnostics = [];

	const registryFile =
		registryPath ||
		// Ejected projects own their registry; the shipped one is the fallback.
		(fs.existsSync(path.join(targetDir, 'src', 'lib', 'data', 'registry.json'))
			? path.join(targetDir, 'src', 'lib', 'data', 'registry.json')
			: path.join(targetDir, 'node_modules', 'fractalthemer', 'src', 'lib', 'data', 'registry.json'));
	const { tokens, ownLayerClasses, layerOf, fileOfLayer } = loadRegistry(registryFile);

	// The canonical base is what THIS package ships — never the target's
	// compiled registry, which absorbs every local skin and would legitimize
	// exactly the component-declared classes the contract forbids. Canonical
	// own-layer classes are the fractalthemer repo's personal extensions, not
	// consumer vocabulary, so they are excluded too.
	const canonical = loadRegistry(REGISTRY);
	const systemClasses = new Set([...canonical.classes].filter((c) => !canonical.ownLayerClasses.has(c)));

	const own = ownPath || path.join(targetDir, 'src', 'lib', 'styles', '_08_own.sass');
	let ownContent = '';
	if (fs.existsSync(own)) ownContent = fs.readFileSync(own, 'utf8');

	// The extension stylesheet is privileged (like the system layers): its
	// classes join the allowlist, and its values are the project's sanctioned
	// own. The ONE thing it cannot do is shadow a system class name — so the
	// collision base is the canonical system (own layers excluded).
	const ownClasses = harvestOwnClasses(ownContent);
	const collisionBase = systemClasses;
	for (const name of ownClasses) {
		if (!collisionBase.has(name)) continue;
		diagnostics.push({
			rule: 'ft/own-conflict',
			severity: 'error',
			file: rel(targetDir, own),
			found: `.${name}`,
			rationale: `".${name}" already exists in the fractalthemer registry. Layer 08 extends the system; it never shadows it — a shadow would silently fork the meaning of a system class.`,
			suggestion: `Rename your class (e.g. ".own-${name}" or a project prefix), or drop it if the system class already covers the intent.`
		});
	}

	// Allowlist = canonical system classes ∪ the project's own layer ∪ the
	// harvested _08_own.sass declarations. Classes that live only in
	// project-specific layers (skins, docs surfaces) have NO declaration
	// rights — they are reported as ft/declaration-outside-own, naming the
	// layer file, instead of a bare unknown-class.
	const allowed = new Set(systemClasses);
	const skinDeclared = new Map();
	for (const [name, layerId] of layerOf) {
		if (ownLayerClasses.has(name)) {
			allowed.add(name);
		} else if (canonical.layerIds.has(layerId)) {
			// A system layer, possibly edited by the ejected project — still the
			// system (eject mode means "own the files").
			allowed.add(name);
		} else {
			skinDeclared.set(name, fileOfLayer.get(layerId) || layerId);
		}
	}
	for (const name of ownClasses) allowed.add(name);
	const localProps = new Set();
	const files = walk(targetDir, (name) => SVELTE.test(name) || STYLESHEET.test(name));

	// In an EJECTED project, src/lib/styles + src/lib/palette ARE the system —
	// privileged for token purity, exactly like the layer partials in-repo.
	const systemPrefixes = ['src/lib/styles/', 'src/lib/palette/'];
	const isSystemStylesheet = (file) => {
		const relFile = rel(targetDir, file).replaceAll(path.sep, '/');
		return systemPrefixes.some((p) => relFile.startsWith(p));
	};

	for (const file of files) {
		if (path.resolve(file) === path.resolve(own) || isSystemStylesheet(file)) continue;
		const content = fs.readFileSync(file, 'utf8');
		if (STYLESHEET.test(file)) TokenLinter.collectDefinedProps(content, localProps);
	}

	const tokenLinter = new TokenLinter(targetDir, { tokens: new Set([...tokens, ...localProps]) });

	for (const file of files) {
		const relPath = rel(targetDir, file);
		const isOwn = path.resolve(file) === path.resolve(own);

		if (SVELTE.test(file)) {
			const source = fs.readFileSync(file, 'utf8');
			const { diagnostics: svelteDiags, classes: used } = lintSvelteFile(relPath, source);
			diagnostics.push(...svelteDiags);

			for (const name of used) {
				if (allowed.has(name)) continue;
				const declaredIn = skinDeclared.get(name);
				if (declaredIn) {
					diagnostics.push({
						rule: 'ft/declaration-outside-own',
						severity: 'error',
						file: relPath,
						found: `.${name}`,
						rationale: `".${name}" is declared in ${declaredIn}, which is not a system layer. Components must compose fractalthemer's classes — a project-specific declaration beside the system defeats it.`,
						suggestion: `Delete the declaration in ${declaredIn} and compose the element from registry classes; if a capability is genuinely missing from the system, add it to _08_own.sass (or propose it as a system class).`
					});
					continue;
				}
				const closest = findClosestMatches(name, allowed, 3, 4);
				const suggestion =
					closest.length > 0
						? `Did you mean '${closest[0]}'?`
						: `Class ".${name}" is neither a fractalthemer class nor declared in _08_own.sass. Use a system class, or declare the addition in _08_own.sass.`;
				diagnostics.push({
					rule: 'ft/unknown-class',
					severity: 'error',
					file: relPath,
					found: `.${name}`,
					rationale:
						'Projects consuming fractalthemer style only with system classes plus declared _08_own extensions — never ad-hoc styling.',
					suggestion
				});
			}
			continue;
		}

		// Stylesheets. The literal-parse rule bites EVERYWHERE — including the
		// privileged files — because a literally-emitted function call is never
		// legitimate, not even in the system layers. Token purity and
		// ft/hardcoded-radius exempt the privileged set (the own file and, in
		// an ejected project, the system directories, which legitimately own
		// literal radii and raw values).
		const isPrivileged = isOwn || isSystemStylesheet(file);
		const stylesheet = fs.readFileSync(file, 'utf8');
		diagnostics.push(...lintUninterpolatedFunctions(relPath, stylesheet));
		if (isPrivileged) continue;
		diagnostics.push(...tokenLinter.lintFile(relPath, stylesheet));
		diagnostics.push(...lintHardcodedRadius(relPath, stylesheet));
	}

	return diagnostics;
}

// --- entry -------------------------------------------------------------------

const args = process.argv.slice(2);
if (args.includes('--help') || args.includes('-h')) {
	usage();
	process.exit(0);
}

if (args[0] === 'eject') {
	await runEject(args.slice(1));
	process.exit(0);
}

if (args[0] === 'mode') {
	await runModeInstall(args.slice(1));
	process.exit(0);
}

if (args[0] === 'browser') {
	await runBrowser(args.slice(1));
	process.exit(0);
}

// `lint` is an optional subcommand — `fractalthemer lint src/` and
// `fractalthemer src/` mean the same thing.
if (args[0] === 'lint') args.shift();

// Parse: flags with a value, then remaining positionals.
const flagValue = new Map([['--own', null], ['--registry', null]]);
const positional = [];
for (let i = 0; i < args.length; i++) {
	if (flagValue.has(args[i])) {
		flagValue.set(args[i], args[++i]);
	} else if (!args[i].startsWith('--')) {
		positional.push(args[i]);
	} else if (args[i] !== '--json') {
		console.error(`Unknown option: ${args[i]}`);
		usage();
		process.exit(2);
	}
}

const json = args.includes('--json');
const ownPath = flagValue.get('--own') ? path.resolve(flagValue.get('--own')) : undefined;
const registryPath = flagValue.get('--registry') ? path.resolve(flagValue.get('--registry')) : undefined;

let diagnostics;
if (positional.length === 0) {
	diagnostics = await lintSelf();
} else {
	diagnostics = lintConsumer(path.resolve(positional[0]), { ownPath, registryPath });
}

reportDiagnostics(diagnostics, { json });
process.exit(diagnostics.some((d) => d.severity === 'error') ? 1 : 0);
