// Registry loader — the reference table for every class/token check.
//
// src/lib/data/registry.json is generated by scripts/build-registry.mjs and is
// the complete inventory of what the styles system emits. The linter NEVER
// hand-parses the SASS sources for class names: the registry is the contract,
// and if the registry is stale that is itself a violation (see cli.mjs).

import fs from 'node:fs';

/**
 * @param {string} registryPath Absolute path to registry.json.
 * @returns {{ classes: Set<string>, tokens: Set<string>, ownLayerClasses: Set<string> }}
 *   `ownLayerClasses` are the classes that came from an `_08_own` layer —
 *   excluded from the collision check, since a project's own declarations
 *   legitimately enter its own registry.
 */
export function loadRegistry(registryPath) {
	if (!fs.existsSync(registryPath)) {
		throw new Error(`registry.json not found at ${registryPath} — run "pnpm registry" first.`);
	}

	const data = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
	const classes = new Set();
	const tokens = new Set();
	const ownLayerClasses = new Set();

	for (const layer of data.layers || []) {
		const isOwnLayer = /own/.test(layer.id || '') || /own/.test(layer.file || '');
		for (const item of layer.items || []) {
			if (item.kind === 'class') {
				const name = item.name.replace(/^\./, '');
				classes.add(name);
				if (isOwnLayer) ownLayerClasses.add(name);
			} else if (item.kind === 'token') {
				tokens.add(item.name);
			}
		}
	}

	return { classes, tokens, ownLayerClasses };
}
